site_name: Nzuri Automation Source Code Docs
repo_url: https://github.com/Nzuri-Codebase/decentralize-code-docs.git

nav:
  - Home: index.md
  - Daily Late Tasks:
      - Overview: late-tasks/index.md
      - Usage: late-tasks/main.md
  - Weekly Status Report:
      - Overview: status-report/index.md
      - Usage: status-report/main.md
  - Decentralize-Nzuri:
      - Overview: Decentralize-Nzuri/index.md
      - Deployment:
          - Docker: Decentralize-Nzuri/deployment/docker.md
          - Azure: Decentralize-Nzuri/deployment/azure.md
      - Streamlit:
          - Overview: Decentralize-Nzuri/streamlit/index.md
          - Honda:
              - Overview: Decentralize-Nzuri/streamlit/honda/index.md
              - Ask Dave:
                  - Ask Dave docs: Decentralize-Nzuri/streamlit/honda/ask-dave/ask_dave.md
              - High Deliverability:
                  - High Deliverability docs: Decentralize-Nzuri/streamlit/honda/high-deliverability/high_del.md
              - Informed Delivery:
                  - Informed Delivery docs: Decentralize-Nzuri/streamlit/honda/informed-delivery/informed.md
              - Remedy Spikes:
                  - Remedy Spikes docs: Decentralize-Nzuri/streamlit/honda/remedy-spikes/remedy_spikes.md

              - Setup: Decentralize-Nzuri/streamlit/honda/setup.md
              - Usage: Decentralize-Nzuri/streamlit/honda/usage.md
              - Troubleshooting: Decentralize-Nzuri/streamlit/honda/troubleshooting.md
          - Nissan:
              - Overview: Decentralize-Nzuri/streamlit/nissan/index.md
              - Apprentice Graduates Placement:
                  - Apprentice Graduates Placement docs: Decentralize-Nzuri/streamlit/nissan/apprentice-graduates-placement/placement.md
              - ROI:
                  - ROI docs: Decentralize-Nzuri/streamlit/nissan/roi/roi.md

              - Setup: Decentralize-Nzuri/streamlit/nissan/setup.md
              - Usage: Decentralize-Nzuri/streamlit/nissan/usage.md
              - Troubleshooting: Decentralize-Nzuri/streamlit/nissan/troubleshooting.md
      - Flask:
          - Overview: Decentralize-Nzuri/flask/index.md
      - InfluxDB:
          - Overview: Decentralize-Nzuri/influxdb/index.md

theme:
  name: readthedocs
  features:
  - navigation.tabs
  - navigation.sections
  - navigation.expand
  - toc.integrate
  palette:
    scheme: default  # Light mode
    primary: indigo
    accent: blue
  font:
    text: Roboto
    code: Roboto Mono
  extra_css:
    - stylesheets/extra.css

plugins:
  - search

markdown_extensions:
  - toc:
      permalink: true
  - admonition  # Allows adding notes/warnings
  - codehilite  # Syntax highlighting for code blocks
